#ifndef COLORS_HPP
#define COLORS_HPP

#define LINE_COLOR_PAIR 1
#define STACK_COLOR_PAIR 2
#define TITLE_COLOR_PAIR 3
#define TERMINAL_COLOR_PAIR 4
#define CODE_COLOR_PAIR 5
#define CODE_CHANGE_PAIR 6
#define CODE_CMD_PAIR 7
#define CODE_PATH_PAIR 8
#define CODE_SPECIAL_PAIR 9
#define CODE_CURSOR_PAIR 10
#define CODE_CROSS_PAIR 11
#define CODE_RUNNER_PAIR 12
#define MENU_COLOR_PAIR 13
#define MENU_SELECTED_PAIR 14
#define CODE_NEGATIVE_PAIR 15
#define HELP_COLOR_PAIR 16

#endif
